name: alfred-workflow

services:
  node:
    type: node:9
    run: yarn

tooling:
  yarn:
    description: 'Execute yarn within container'
    service: node
  node:
    description: 'Execute node within container'
    service: node
  npm:
    description: 'Execute npm within container'
    service: node
